---
# Defines deployment design and assigns role to server groups

- hosts: mons
  sudo: True
  roles:
  - ceph-mon
  - { role: ceph-restapi, when: restapi_group_name is defined and restapi_group_name in group_names }
  #serial: 1 # ENABLE THIS WHEN DEPLOYING MONITORS ON DOCKER CONTAINERS

- hosts: osds
  sudo: True
  roles:
  - ceph-osd

- hosts: mdss
  sudo: True
  roles:
  - ceph-mds

- hosts: rgws
  sudo: True
  roles:
  - ceph-rgw

- hosts: swift
  sudo: True
  roles:
  - ceph-swift
