  - name: create  object server config from template
    template: src=swift_ceph.conf.j2 dest=/etc/swift/object-server/5.conf owner={{ swift_username }} group={{ swift_group }} mode=0644

  - name: add new swift.conf file with swift-ceph storage policy
    template: src=swift.conf.j2 dest=/etc/swift/swift.conf owner={{ swift_username }} group={{ swift_group }} mode=0644

  - name: create swift-ceph object ring creation script
    template: src=swift_ceph_remakering.j2 dest=/home/{{ swift_username }}/bin/swift_ceph_remakering owner={{ swift_username }} group={{ swift_group }} mode=0777

  - name: remake swift ceph object ring
    command: /home/{{ swift_username }}/bin/swift_ceph_remakering

  - name: check if swiftonfile is already cloned
    stat: path={{ source_dir }}/swift-ceph-backend
    register: swift_ceph_cloned

  - name: git clone swift-ceph-backend
    git: repo=https://github.com/stackforge/swift-ceph-backend.git dest={{ source_dir }}/swift-ceph-backend accept_hostkey=yes
    when: not swift_ceph_cloned.stat.exists

#  - name: add gerrit repo to swiftonfile clone
#    command: git remote add gerrit ssh://{{ openstack_username }}@review.openstack.org:29418/stackforge/swiftonfile.git chdir={{ source_dir }}/swiftonfile
#    when: configure_gerrit and not swiftonfile_cloned.stat.exists

  - name: build a development installation of swift-ceph
    command: python setup.py develop chdir={{ source_dir }}/swift-ceph-backend

  - name: set correct ownership of repos
    file: path={{ source_dir }}/{{ item }} owner={{ swift_username }} group={{ swift_group }} recurse=yes
    with_items:
    - swift-ceph-backend
